FROM python:3.12-slim

WORKDIR /app

COPY docker/requirements.preprocessing.txt .
RUN pip install --no-cache-dir -r requirements.preprocessing.txt

COPY src/ /app/src/
COPY params.yaml .
COPY setup.py .
COPY .env /app/.env

#CMD ["python", "-m", "src.data.make_dataset"]
