FROM python:3.12-slim

WORKDIR /app

COPY docker/requirements.dataloading.txt .
RUN pip install --no-cache-dir -r requirements.dataloading.txt

COPY src/ /app/src/
COPY params.yaml .
COPY setup.py .
COPY .env /app/.env

#CMD ["python", "-m", "src.data.import_raw_data"]
