FROM python:3.12-slim

WORKDIR /app

COPY docker/requirements.mlflow.txt .
RUN pip install --no-cache-dir -r requirements.mlflow.txt
RUN pip install mlflow

#COPY . .
COPY src/ /app/src/ 
COPY docker-compose.yml .
COPY params.yaml .
COPY setup.py .
COPY .env /app/.env

EXPOSE 5000

CMD ["mlflow", "ui", "--host", "0.0.0.0", "--port", "5000"]
